name: agora
description: A new Flutter project.
publish_to: 'none' # Prevent accidental publishing to pub.dev

# App versioning: major.minor.patch+build
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Commonly used packages
  cupertino_icons: ^1.0.8           # iOS-style icons
  pinput: ^5.0.1                    # OTP input fields
  image_picker: ^1.1.2             # Pick images from gallery or camera
  another_flushbar: ^1.10.28       # Toast-like bars for feedback
  flutter_polls: ^0.1.6            # Poll widget support
  logger: ^2.5.0                   # Advanced logging

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_svg: ^2.0.17             # Render SVG images
  flutter_lints: ^5.0.0            # Recommended lint rules for Dart & Flutter

flutter:

  uses-material-design: true       # Include Material icons and themes

  # Asset definitions
  assets:
    - assets/images/image 7.png
    - assets/images/Frame 243.png
    - assets/images/Banners.png
    - assets/images/image 10.png
    - assets/images/agora.png
    - assets/images/google logo.png
    - assets/images/apple logo.png
    - assets/images/Ellipse 729.png

    # Follow Images
    - assets/images/follow images/person1.png
    - assets/images/follow images/img.png
    - assets/images/follow images/person2.png
    - assets/images/follow images/img_1.png
    - assets/images/follow images/unknown profile.jpg
    - assets/images/follow images/Rectangle 110482.png
    - assets/images/follow images/Ali.png
    - assets/images/follow images/Abdullah.png
    - assets/images/follow images/Ahmad.png
    - assets/images/follow images/UiUx2.png
    - assets/images/follow images/2.png
    - assets/images/follow images/3.png
    - assets/images/follow images/4.png
    - assets/images/follow images/5.png
    - assets/images/follow images/6.png
    - assets/images/follow images/7.png
    - assets/images/follow images/8.png

    # Confirmation Images
    - assets/images/confirmation image/Star 8.svg
    - assets/images/confirmation image/Star 9.png
    - assets/images/confirmation image/Star 8.png

    # Homepage Images
    - assets/images/Homepage images/Oval.png
    - assets/images/Homepage images/Oval2.png
    - assets/images/Homepage images/Oval3.png
    - assets/images/Homepage images/Rectangle 42.png
    - assets/images/Homepage images/computer.jpg
    - assets/images/Homepage images/uiUX.png
    - assets/images/Homepage images/Group 82.png

    # Gallery Images
    - assets/images/Gallery1.png
    - assets/images/Gallery2.png
    - assets/images/Gallery3.png
    - assets/images/Gallery4.png

    # Event Images
    - assets/images/Event Images/event.png
    - assets/images/Event Images/event2.png
    - assets/images/Event Images/event3.png

    # Payment Method Images
    - assets/images/Appl.png
    - assets/images/Google.png
    - assets/images/MasterCard.png
    - assets/images/PayPal.png

    # SVG Icons
    - assets/images/Svg/Vector.svg
    - assets/images/Svg/Vector1.svg
    - assets/images/Svg/edit.svg
    - assets/images/Svg/add.svg
    - assets/images/Svg/setting-2.svg
    - assets/images/Svg/activity.svg
    - assets/images/Svg/adm.svg
    - assets/images/Svg/rem.svg

    # Campaign and Analytics
    - assets/images/CompaignDetails.png
    - assets/images/chart.png
    - assets/images/spent.png

    # Create Post Images
    - assets/images/CreatePostImag/crPost1.png
    - assets/images/CreatePostImag/crPost2.png
    - assets/images/CreatePostImag/crPost3.png
    - assets/images/AsifWedd.png

    # Miscellaneous
    - assets/images/map.png
    - assets/images/CARD.png

  # Custom font configuration
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
